from enum import Enum

class ChatState(str, Enum):
    START = "START"

    ASK_NAME = "ASK_NAME"
    ASK_PHONE = "ASK_PHONE"
    ASK_REASON = "ASK_REASON"
    
    ASK_DATE = "ASK_DATE"
    ASK_HALF_DAY = "ASK_HALF_DAY"
    ASK_TIME = "ASK_TIME"

    CONFIRMATION = "CONFIRMATION"
    CHANGE_WHAT = "CHANGE_WHAT"

    ASK_DATE_EDIT = "ASK_DATE_EDIT"
    ASK_TIME_EDIT = "ASK_TIME_EDIT"
    ASK_REASON_EDIT = "ASK_REASON_EDIT"

    CONFIRMED = "CONFIRMED"
